name: Randomtp1_16_5
version: ${project.version}
main: kun.randomtp1_16_5.Randomtp1_16_5
api-version: 1.16
commands:
  exerandomTp:
    description: /exerandomTp
    usage: /exerandomTp
    permission: Randomtp.operator
    permission-message: You don't have <permission>
  setRadius:
    description: /setRadius <TPの半径>
    usage: /setRadius
    permission: Randomtp.operator
    permission-message: You don't have <permission>
permissions:
  Randomtp.operator:
    description: Randomtp operator
    default: op
  Randomtp.all:
    description: all user
    default: true
